# sycl-toolkit-devel package
# This is a sub-package that only defines [package], not [workspace]

[package]
name = "sycl-toolkit-devel"
version = "2025.0.0"

[package.build]
backend = { name = "pixi-build-rattler-build", version = "*" }

[package.run-dependencies]
sycl-toolkit-libs = { path = "../libs" }
