# naga-sycl-toolkit-devel package
# This is a sub-package that only defines [package], not [workspace]

[package]
name = "naga-sycl-toolkit-devel"
version = "2025.12.1"

[package.build]
backend = { name = "pixi-build-rattler-build", version = "*" }

[package.run-dependencies]
naga-sycl-toolkit-libs = { path = "../libs" }
